name: Artifactory Check CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    types:
      - opened
      - synchronize
    branches: [$default-branch]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    run: echo "Dependabot detected, skipping rest of job"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Checkout shared Availity tools
        uses: actions/checkout@v2
        with:
          repository: Availity/.github
          token: ${{ secrets.BOT_TOKEN }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: tools

      - name: Run registry checker
        working-directory: tools
        run: ./scripts/artifactory-check.sh
